/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
  theme: {
    fontSize: {
      'tiny': '8px',
      'xs': '12px',
      'sm': '14px',
      'base': '18px',
      'md': '20px',
      'lg': '24px',
      'xl': '33px',
      '2xl': '44px',
      '3xl': '58px',
      '4xl': '75px',
      '5xl': '98px',
      '6xl': '128px',
    },
    extend: {
      fontFamily: {
        bricolage: ["var(--font-bricolage)", "sans-serif"],
        poppins: ["var(--font-poppins)", "serif"],
      },
      colors: {
        primaryLightBlue: "#21AFFF",
        primaryBlue: "#2B0DE9",
        primaryPurple: "#AC59FF",
        primaryTextDarkBlue: "#0A004D",
      },
      boxShadow: {
        'inner-button': "inset 0 0 4px 0 rgba(0, 0, 0, 0.25)",
      },
    },
  },
  plugins: [require("daisyui")],
};
